# Configuration for https://github.com/rhysd/actionlint run by pre-commit
self-hosted-runner:
  labels:
    - ubuntu-24.04       # GitHub-Hosted runner for public workflows - DEPRECATED
    - ubuntu-24.04-large # GitHub-Hosted Large runner for public workflows performing authenticated actions - DEPRECATED
    - sonar-runner-large # GitHub-Hosted Large with Docker-in-Docker enabled - DEPRECATED
    - github-ubuntu-latest-s
    - github-windows-latest-s
