---
name: Promote
description: GitHub Action to promote a project
inputs:
  promote-pull-request:
    description: Whether to promote pull request artifacts. Requires `deploy-pull-request` input to be set to `true` in the build action.
    default: 'false'
  multi-repo:
    description: If true, promotes to public and private repositories. For projects with both public and private artifacts.
  artifactory-deploy-repo:
    description: Repository to deploy to. If not set, it will be retrieved from the build info.
  artifactory-target-repo:
    description: Target repository for the promotion. If not set, it will be determined based on the branch type and the deploy repository.
  build-name:
    description: Name of the build to promote. Defaults to the repository name.
    default: ''

runs:
  using: composite
  steps:
    - name: Set local action paths
      id: set-path
      shell: bash
      run: |
        echo "::group::Fix for using local actions"
        echo "GITHUB_ACTION_PATH=$GITHUB_ACTION_PATH"
        echo "github.action_path=${{ github.action_path }}"
        ACTION_PATH_PROMOTE="${{ github.action_path }}"
        echo "ACTION_PATH_PROMOTE=$ACTION_PATH_PROMOTE"
        echo "ACTION_PATH_PROMOTE=$ACTION_PATH_PROMOTE" >> "$GITHUB_ENV"
        host_actions_root="$(dirname "$ACTION_PATH_PROMOTE")"
        echo "host_actions_root=$host_actions_root" >> "$GITHUB_OUTPUT"

        mkdir -p ".actions"
        ln -sf "$host_actions_root/get-build-number" .actions/get-build-number
        ln -sf "$host_actions_root/shared" .actions/shared
        ls -la .actions/*
        echo "::endgroup::"

    - name: Set build parameters
      shell: bash
      run: |
        cp "$ACTION_PATH_PROMOTE/mise.local.toml" mise.local.toml
    - uses: ./.actions/get-build-number
      with:
        host-actions-root: ${{ steps.set-path.outputs.host_actions_root }}
    - uses: SonarSource/vault-action-wrapper@320bd31b03e5dacaac6be51bbbb15adf7caccc32 # 3.1.0
      id: secrets
      with:
        secrets: |
          development/artifactory/token/{REPO_OWNER_NAME_DASH}-promoter access_token | ARTIFACTORY_PROMOTE_ACCESS_TOKEN;
          development/github/token/{REPO_OWNER_NAME_DASH}-promotion token | GITHUB_TOKEN;
    - uses: jdx/mise-action@5ac50f778e26fac95da98d50503682459e86d566 # v3.2.0
      with:
        version: 2025.7.12
    - name: Promote artifacts
      shell: bash
      env:
        ARTIFACTORY_PROMOTE_ACCESS_TOKEN: ${{ fromJSON(steps.secrets.outputs.vault).ARTIFACTORY_PROMOTE_ACCESS_TOKEN }}
        GITHUB_TOKEN: ${{ fromJSON(steps.secrets.outputs.vault).GITHUB_TOKEN }}
        DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
        MULTI_REPO_PROMOTE: ${{ inputs.multi-repo }}
        ARTIFACTORY_DEPLOY_REPO: ${{ inputs.artifactory-deploy-repo }}
        ARTIFACTORY_TARGET_REPO: ${{ inputs.artifactory-target-repo }}
        PROMOTE_PULL_REQUEST: ${{ inputs.promote-pull-request }}
        BUILD_NAME: ${{ inputs.build-name || github.event.repository.name }}
      run: |
        "$ACTION_PATH_PROMOTE/promote.sh"
