name: PR Cleanup
description: Cleanup caches and artifacts associated with a pull request

runs:
  using: composite
  steps:
    - name: Cleanup caches
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
        GH_FORCE_TTY: 140
        CACHE_REF: refs/pull/${{ github.event.pull_request.number }}/merge
      run: ${GITHUB_ACTION_PATH}/cleanup.sh
