extends: default
ignore-from-file: .gitignore
locale: en_US.UTF-8
rules:
  anchors:
    forbid-duplicated-anchors: true
    forbid-unused-anchors: true
  braces: &spaces-insde-empty
    min-spaces-inside-empty: 0
    max-spaces-inside-empty: 0
  brackets:
    *spaces-insde-empty
  comments:
    min-spaces-from-content: 1
  document-start: disable
  indentation:
    spaces: 2
  line-length:
    max: 140
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: false
  quoted-strings:
    quote-type: single
    required: only-when-needed
  truthy:
    check-keys: false
