---
name: Get build number
description: GitHub Action to get the build number for a repository
outputs:
  BUILD_NUMBER:
    description: The build number, incremented or reused if already cached
    value: ${{ steps.export.outputs.BUILD_NUMBER }}

runs:
  using: composite
  steps:
    # Reuse current build number in case of rerun
    - name: Get cached build number
      uses: actions/cache/restore@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      id: current-build-number
      with:
        path: build_number.txt
        key: build-number-${{ github.run_id }}

    # Otherwise, increment the build number
    - name: Get secrets from Vault
      id: secrets
      if: steps.current-build-number.outputs.cache-hit != 'true'
      uses: SonarSource/vault-action-wrapper@d6d745ffdbc82b040df839b903bc33b5592cd6b0 # 3.0.2
      with:
        secrets: development/github/token/{REPO_OWNER_NAME_DASH}-build-number token | github_token;
    - name: Get new build number
      if: steps.current-build-number.outputs.cache-hit != 'true'
      shell: bash
      env:
        GITHUB_TOKEN: ${{ steps.current-build-number.outputs.cache-hit != 'true' && fromJSON(steps.secrets.outputs.vault).github_token
          || '' }}
        GITHUB_REPOSITORY: ${{ github.repository }}
      run: ${GITHUB_ACTION_PATH}/get_build_number.sh

    - name: Export build number
      id: export
      shell: bash
      run: |
        BUILD_NUMBER=$(cat build_number.txt)
        echo "BUILD_NUMBER: ${BUILD_NUMBER}"
        echo "BUILD_NUMBER=${BUILD_NUMBER}" >> "$GITHUB_ENV"
        echo "BUILD_NUMBER=${BUILD_NUMBER}" >> "$GITHUB_OUTPUT"
    - name: Save build number to cache
      uses: actions/cache/save@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      if: steps.current-build-number.outputs.cache-hit != 'true'
      with:
        path: build_number.txt
        key: build-number-${{ github.run_id }}
