---
name: Get build number
description: GitHub Action to get the build number for a repository
outputs:
  BUILD_NUMBER:
    description: The build number, incremented or reused if already cached
    value: ${{ steps.export.outputs.BUILD_NUMBER }}
inputs:
  host-actions-root:
    description: Path to the actions folder on the host (used when called from another local action)
    default: ''

runs:
  using: composite
  steps:
    - name: Set local action paths
      id: set-path
      shell: bash
      run: |
        echo "::group::Fix for using local actions"
        echo "GITHUB_ACTION_PATH=$GITHUB_ACTION_PATH"
        echo "github.action_path=${{ github.action_path }}"
        ACTION_PATH_GET_BUILD_NUMBER="${{ github.action_path }}"
        host_actions_root="${{ inputs.host-actions-root }}"
        if [ -z "$host_actions_root" ]; then
          host_actions_root="$(dirname "$ACTION_PATH_GET_BUILD_NUMBER")"
        else
          ACTION_PATH_GET_BUILD_NUMBER="$host_actions_root/get-build-number"
        fi
        echo "ACTION_PATH_GET_BUILD_NUMBER=$ACTION_PATH_GET_BUILD_NUMBER"
        echo "ACTION_PATH_GET_BUILD_NUMBER=$ACTION_PATH_GET_BUILD_NUMBER" >> "$GITHUB_ENV"
        echo "::endgroup::"

    # Reuse build number from environment if provided (e.g. from a parent workflow)
    - name: Save build number from environment to file
      id: from-env
      if: env.BUILD_NUMBER != ''
      shell: bash
      run: |
        echo "BUILD_NUMBER ${BUILD_NUMBER} provided from environment, skipping both increment and save to cache."
        echo "${BUILD_NUMBER}" > build_number.txt
        echo "skip=true" >> $GITHUB_OUTPUT

    # Reuse current build number in case of rerun
    - name: Get cached build number
      if: steps.from-env.outputs.skip != 'true'
      uses: actions/cache/restore@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      id: current-build-number
      with:
        path: build_number.txt
        key: build-number-${{ github.run_id }}
        enableCrossOsArchive: true

    # Otherwise, increment the build number
    - uses: SonarSource/vault-action-wrapper@320bd31b03e5dacaac6be51bbbb15adf7caccc32 # 3.1.0
      id: secrets
      if: steps.from-env.outputs.skip != 'true' && steps.current-build-number.outputs.cache-hit != 'true'
      with:
        secrets: development/github/token/{REPO_OWNER_NAME_DASH}-build-number token | github_token;
    - name: Get new build number
      if: steps.from-env.outputs.skip != 'true' && steps.current-build-number.outputs.cache-hit != 'true'
      shell: bash
      env:
        GITHUB_TOKEN: ${{ steps.current-build-number.outputs.cache-hit != 'true' &&
          steps.secrets.outputs.vault && fromJSON(steps.secrets.outputs.vault).github_token || '' }}
      run: ${ACTION_PATH_GET_BUILD_NUMBER}/get_build_number.sh

    - name: Export build number
      id: export
      shell: bash
      run: |
        BUILD_NUMBER=$(cat build_number.txt)
        echo "BUILD_NUMBER: ${BUILD_NUMBER}"
        echo "BUILD_NUMBER=${BUILD_NUMBER}" >> "$GITHUB_ENV"
        echo "BUILD_NUMBER=${BUILD_NUMBER}" >> "$GITHUB_OUTPUT"

    - name: Save build number to cache
      uses: actions/cache/save@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      if: steps.from-env.outputs.skip != 'true' && steps.current-build-number.outputs.cache-hit != 'true'
      with:
        path: build_number.txt
        key: build-number-${{ github.run_id }}
        enableCrossOsArchive: true
