---
name: Get build number
description: GitHub Action to get the build number for a repository
inputs:
  SCRIPT_PATH:
    description: script path to get_build_number.sh (defaults to the action directory)
    default: ''
outputs:
  BUILD_NUMBER:
    description: The build number, incremented or reused if already cached
    value: ${{ steps.export.outputs.BUILD_NUMBER }}

runs:
  using: composite
  steps:
    - id: setup
      shell: bash
      run: |
        script_path="${{ inputs.SCRIPT_PATH }}"
        if [ -z "$script_path" ]; then
          script_path="$GITHUB_ACTION_PATH"
        else
          script_path="$script_path/get-build-number"
        fi
        echo "script_path: ${script_path}"
        echo "script_path=${script_path}" >> "$GITHUB_OUTPUT"

        echo "DEBUG get-build-number"
        echo "github.workspace: ${{ github.workspace }}"
        echo "GITHUB_WORKSPACE: ${GITHUB_WORKSPACE}"
        echo "github.action_path: ${{ github.action_path }}"
        echo "GITHUB_ACTION_PATH: ${GITHUB_ACTION_PATH}"
        echo "PWD: $(pwd)"
        echo
        echo "GITHUB_ACTION_PATH/localB.sh ${GITHUB_ACTION_PATH}/get_build_number.sh $([ -e "${GITHUB_ACTION_PATH}/get_build_number.sh" ] && echo 'OK' || echo 'KO')"
        echo "github.action_path/localB.sh ${{github.action_path}}/get_build_number.sh $([ -e "${{github.action_path}}/get_build_number.sh" ] && echo 'OK' || echo 'KO')"
        echo "script_path/localB/localB.sh ${script_path}/get-build-number/get_build_number.sh $([ -e "${script_path}/get-build-number/get_build_number.sh" ] && echo 'OK' || echo 'KO')"
    # Reuse build number from environment if provided (e.g. from a parent workflow)
    - name: Save build number from environment to file
      id: from-env
      if: env.BUILD_NUMBER != ''
      shell: bash
      run: |
        echo "BUILD_NUMBER ${BUILD_NUMBER} provided from environment, skipping both increment and save to cache."
        echo "${BUILD_NUMBER}" > build_number.txt
        echo "skip=true" >> $GITHUB_OUTPUT

    # Reuse current build number in case of rerun
    - name: Get cached build number
      if: steps.from-env.outputs.skip != 'true'
      uses: actions/cache/restore@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      id: current-build-number
      with:
        path: build_number.txt
        key: build-number-${{ github.run_id }}
        enableCrossOsArchive: true

    # Otherwise, increment the build number
    - name: Get secrets from Vault
      id: secrets
      if: steps.from-env.outputs.skip != 'true' && steps.current-build-number.outputs.cache-hit != 'true'
      uses: SonarSource/vault-action-wrapper@320bd31b03e5dacaac6be51bbbb15adf7caccc32 # 3.1.0
      with:
        secrets: development/github/token/{REPO_OWNER_NAME_DASH}-build-number token | github_token;
    - name: Get new build number
      if: steps.from-env.outputs.skip != 'true' && steps.current-build-number.outputs.cache-hit != 'true'
      shell: bash
      env:
        GITHUB_TOKEN: ${{ steps.current-build-number.outputs.cache-hit != 'true' &&
          steps.secrets.outputs.vault && fromJSON(steps.secrets.outputs.vault).github_token || '' }}
        SCRIPT_PATH: ${{ steps.setup.outputs.script_path }}
      run: $SCRIPT_PATH/get_build_number.sh

    - name: Export build number
      id: export
      shell: bash
      run: |
        BUILD_NUMBER=$(cat build_number.txt)
        echo "BUILD_NUMBER: ${BUILD_NUMBER}"
        echo "BUILD_NUMBER=${BUILD_NUMBER}" >> "$GITHUB_ENV"
        echo "BUILD_NUMBER=${BUILD_NUMBER}" >> "$GITHUB_OUTPUT"

    - name: Save build number to cache
      uses: actions/cache/save@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      if: steps.from-env.outputs.skip != 'true' && steps.current-build-number.outputs.cache-hit != 'true'
      with:
        path: build_number.txt
        key: build-number-${{ github.run_id }}
        enableCrossOsArchive: true
