name: Cleanup PR Resources
on:
  pull_request:
    types:
      - closed

jobs:
  cleanup:
    runs-on: warp-custom-ubuntu-24-04
    permissions:
      actions: write  # Required for deleting caches and artifacts
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          sparse-checkout: pr_cleanup
      - uses: ./pr_cleanup
