name: Cleanup PR Resources
on:
  pull_request:
    types:
      - closed

jobs:
  cleanup:
    runs-on: warp-custom-ubuntu-24-04
    permissions:
      actions: write  # Required for deleting caches and artifacts
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          sparse-checkout: pr_cleanup
      - uses: ./pr_cleanup
