name: Pre-commit Checks
on:
  pull_request:
permissions:
  id-token: write
  contents: read
jobs:
  pre-commit:
    runs-on: warp-custom-ubuntu-24-04
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: ./config-npm
      - uses: SonarSource/gh-action_pre-commit@2ddc0c7fdabce0adfaaa4075a17690972ed9961a # 1.2.0
        with:
          extra-args: >
            --from-ref=origin/${{ github.event.pull_request.base.ref }}
            --to-ref=${{ github.event.pull_request.head.sha }}
