---
name: Test SCA Check
on:
  pull_request:
    paths:
      - .github/workflows/check-sca.yml
      - .github/workflows/test-check-sca.yml

permissions:
  id-token: write
  contents: read

jobs:
  verify-sca:
    uses: ./.github/workflows/check-sca.yml
