name: Unified Dogfooding scans
on:
  schedule:
    - cron: 0 4 * * * # Run the workflow every day at 04:00 UTC
  workflow_dispatch:

jobs:
  unified-platform-dogfooding:
    runs-on: warp-custom-ubuntu-24-04
    name: Unified Platform Dogfooding
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Run IRIS Analysis
        uses: SonarSource/unified-dogfooding-actions/run-iris@03e023516511b1c9da325ad104c2290e3b91688c # 1.1.0
        with:
          primary_project_key: SonarSource_ci-github-actions
          primary_platform: SQC-EU
          shadow1_project_key: SonarSource_ci-github-actions
          shadow1_platform: Next
          shadow2_project_key: SonarSource_ci-github-actions
          shadow2_platform: SQC-US
